from __future__ import annotations
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple
import math
import warnings

Vec2 = Tuple[float, float]

#: Bumped by every Simulation step.  Per-unit memoised queries (operational weapons, crew status)
#: are valid only within one step *and* only while the unit's composition key is unchanged.
STATE_EPOCH = [0]

class Side(str, Enum):
    BLUE = "BLUE"
    RED = "RED"

class UnitState(str, Enum):
    IDLE = "IDLE"
    MOVING = "MOVING"
    DEFENDING = "DEFENDING"
    ATTACKING = "ATTACKING"
    SEARCHING = "SEARCHING"
    ENGAGING = "ENGAGING"
    RETREATING = "RETREATING"
    COMBAT_INEFFECTIVE = "COMBAT_INEFFECTIVE"
    DESTROYED = "DESTROYED"
    AGGREGATED = "AGGREGATED"
    MOUNTING = "MOUNTING"
    DISMOUNTING = "DISMOUNTING"

@dataclass
class WeaponModel:
    """Abstract weapon/capability model.

    Values in the demo are synthetic M&S tuning values, not real weapon performance.
    target_tags describe what the weapon can physically affect.  A rifle-only infantry
    formation therefore has no path to damage an ARMOR element.
    """
    name: str
    capability: str
    range_m: float
    shots_per_min: float
    pk: float
    target_tags: List[str] = field(default_factory=lambda: ["PERSONNEL"])
    max_effect_count: int = 1
    ammo_capacity: int = -1       # -1 = abstract/unlimited
    ammo_remaining: int = -1
    metadata: Dict[str, Any] = field(default_factory=dict)

    @property
    def has_ammo(self) -> bool:
        return self.ammo_remaining != 0

    def expend_round(self) -> bool:
        if self.ammo_remaining == 0:
            return False
        if self.ammo_remaining > 0:
            self.ammo_remaining -= 1
        return True

@dataclass
class FormationElement:
    """A countable TO&E element inside a formation.

    Examples: rifle personnel, AT specialist, tank, artillery piece.  Weapons belong to
    the element that must survive for the capability to remain available.
    """
    eid: str
    name: str
    category: str                 # PERSONNEL or EQUIPMENT
    role: str                     # RIFLE, ANTI_ARMOR, ARMOR, ARTILLERY, AIR_DEFENSE ...
    count: int
    initial_count: int
    combat_value: float = 1.0
    weapons: List[WeaponModel] = field(default_factory=list)
    min_operators: int = 1
    metadata: Dict[str, Any] = field(default_factory=dict)
    # Per-item state is lazily initialized for equipment elements that need component-level
    # damage (e.g. tanks / artillery pieces). Values: OPERATIONAL, MOBILITY_KILL,
    # FIREPOWER_KILL, DISABLED, DESTROYED.
    item_states: List[str] = field(default_factory=list)
    # Stable identity per physical item, parallel to ``item_states``.  List positions shift when
    # a vehicle is detached, so delayed effects (artillery fragments, etc.) address items by id.
    item_ids: List[str] = field(default_factory=list)
    item_serial: int = 0

    def ensure_item_states(self):
        if self.category.upper() != "EQUIPMENT":
            return
        target=max(self.initial_count,self.count)
        if not self.item_states:
            self.item_states=["OPERATIONAL"]*target
        elif len(self.item_states)<target:
            self.item_states.extend(["OPERATIONAL"]*(target-len(self.item_states)))
        self.sync_item_ids()

    def sync_item_ids(self):
        """Keep ``item_ids`` the same length as ``item_states`` (new items get fresh ids)."""
        if len(self.item_ids) > len(self.item_states):
            del self.item_ids[len(self.item_states):]
        while len(self.item_ids) < len(self.item_states):
            self.item_serial += 1
            self.item_ids.append(f"{self.eid}#{self.item_serial}")

    def item_id_at(self, index: int) -> Optional[str]:
        self.sync_item_ids()
        return self.item_ids[index] if 0 <= index < len(self.item_ids) else None

    def index_of_item(self, item_id: str) -> Optional[int]:
        self.sync_item_ids()
        try:
            return self.item_ids.index(str(item_id))
        except ValueError:
            return None

    def remove_item(self, index: int):
        """Remove one physical item and return ``(state, item_id)``."""
        self.sync_item_ids()
        return self.item_states.pop(index), self.item_ids.pop(index)

    def sync_count_from_states(self):
        if self.category.upper()=="EQUIPMENT":
            # An empty item-state list is a valid state after the last physical item has been
            # transferred to a detached vehicle.  Leaving ``count`` untouched here creates a
            # ghost vehicle which can later be regenerated by ensure_item_states().
            self.count=sum(1 for x in self.item_states if x!="DESTROYED")

    @property
    def operational_item_count(self) -> int:
        if self.category.upper()!="EQUIPMENT":
            return self.count
        self.ensure_item_states()
        return sum(1 for x in self.item_states if x=="OPERATIONAL")

    @property
    def fire_capable_item_count(self) -> int:
        if self.category.upper()!="EQUIPMENT":
            return self.count
        self.ensure_item_states()
        return sum(1 for x in self.item_states if x in ("OPERATIONAL","MOBILITY_KILL"))

    @property
    def mobile_item_count(self) -> int:
        if self.category.upper()!="EQUIPMENT":
            return self.count
        self.ensure_item_states()
        return sum(1 for x in self.item_states if x in ("OPERATIONAL","FIREPOWER_KILL"))

    @property
    def alive(self) -> bool:
        return self.count > 0

    @property
    def operational(self) -> bool:
        if self.category.upper() == "PERSONNEL":
            return self.count >= max(1, self.min_operators)
        return self.count > 0

    def active_weapon_system_count(self, weapon: WeaponModel) -> int:
        """Deprecated element-local estimate under historical firing rules.

        Kept only for external callers during migration. This is neither physical
        inventory nor current runtime participation: it cannot see the owning
        unit's crew pools or mount state. Use
        unit.firepower(element, weapon).participants for runtime participation.
        The historical return value is deliberately unchanged until removal.
        """
        warnings.warn(
            "FormationElement.active_weapon_system_count() is deprecated; "
            "use unit.firepower(element, weapon).participants for runtime participation.",
            DeprecationWarning, stacklevel=2,
        )
        inventory_model = str(weapon.metadata.get("inventory_model", "")).upper()
        # Disposable shoulder-launched munitions (AT4/LAW/BDM family) are inventory rounds,
        # not reusable launchers with permanently assigned crews. Any surviving eligible
        # soldier in the owning personnel element may employ a carried round.
        if inventory_model == "DISPOSABLE_ROUNDS":
            rounds = weapon.ammo_remaining if weapon.ammo_remaining >= 0 else weapon.ammo_capacity
            return min(max(0, self.count), max(0, int(rounds)))

        configured = max(0, int(weapon.metadata.get("system_count", 1)))
        if configured <= 0:
            return 0
        if self.category.upper() == "PERSONNEL":
            ops = max(1, int(weapon.metadata.get("operators_per_system", 1)))
            return min(configured, max(0, self.count // ops))
        spp = max(1, int(weapon.metadata.get("systems_per_provider", 1)))
        return min(configured, max(0, self.fire_capable_item_count * spp))

    @property
    def strength(self) -> float:
        return max(0, self.count) * self.combat_value

    @property
    def initial_strength(self) -> float:
        return max(0, self.initial_count) * self.combat_value

    @property
    def tags(self) -> set[str]:
        tags = {self.category.upper(), self.role.upper()}
        tags.update(str(x).upper() for x in self.metadata.get("tags", []))
        return tags

@dataclass
class UnitType:
    name: str
    branch: str
    max_speed_mps: float
    detection_range_m: float
    elements: List[FormationElement] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)

@dataclass
class Order:
    order_id: str
    kind: str
    params: Dict[str, Any] = field(default_factory=dict)
    # Reactive trigger evaluated while the order is active.  Existing BML semantics are preserved:
    # on_true fires when all conditions become true; on_false remains a completion-time branch.
    conditions: List[Dict[str, Any]] = field(default_factory=list)
    on_true: Optional[Dict[str, Any]] = None
    on_false: Optional[Dict[str, Any]] = None
    # BML execution constraints / command intent.  These are UI- and simulation-framework neutral.
    directives: Dict[str, Any] = field(default_factory=dict)
    phase_id: Optional[str] = None
    start_at_s: Optional[float] = None
    deadline_s: Optional[float] = None
    on_deadline: Optional[Dict[str, Any]] = None
    deadline_reported: bool = field(default=False, compare=False, repr=False)


@dataclass
class Track:
    """Per-observer fog-of-war contact. Ground truth is never exposed to combat logic directly."""
    track_id: str
    target_id: str
    estimated_pos: Vec2
    position_error_m: float
    classification: str = "UNKNOWN"
    confidence: float = 0.0
    last_seen_time: float = 0.0
    observations: int = 0
    source: str = "LOCAL"           # LOCAL / SHARED / COUNTER_BATTERY / PROXIMITY
    # Perceptual geometry of the last direct observation. CLOSE means the observer acquired the
    # contact through its short-range all-round awareness zone; FORWARD means the principal
    # directional observation sector. Shared/other sensors intentionally do not inherit CLOSE.
    observation_zone: str = "UNKNOWN"  # CLOSE / FORWARD / SHARED / SENSOR / UNKNOWN
    state: str = "DETECTED"         # DETECTED / CLASSIFIED / IDENTIFIED / STALE / LOST / INFERRED / DESTROYED
    # Belief persistence is deliberately separate from tactical actionability. A commander may
    # still believe an enemy formation exists long after its last firing-quality track is stale.
    belief_confidence: float = 0.0
    existence_confirmed: bool = False
    last_confirmed_time: float = 0.0
    # Element tags the observer saw at the last observation (a snapshot, not live inventory).
    # ``None`` means composition unknown; decision logic then falls back to the classification.
    perceived_tags: Optional[Tuple[str, ...]] = None
    # The confidence at the last observation anchors half-life decay across repeated scans.
    belief_anchor_confidence: Optional[float] = None

    def actionable(self, now: float, max_age: float = 45.0, min_confidence: float = 0.35) -> bool:
        return self.state not in ("LOST", "DESTROYED") and (now - self.last_seen_time) <= max_age and self.confidence >= min_confidence

@dataclass
class Unit:
    uid: str
    name: str
    side: Side
    echelon: str
    unit_type: UnitType
    pos: Vec2
    heading_deg: float = 0.0
    # Direction (world degrees, +x=0, +y=90) in which the formation is primarily observing.
    # This is distinct from vehicle/body heading: halted troops and turrets may watch elsewhere.
    watch_heading_deg: float = 0.0
    state: UnitState = UnitState.IDLE
    parent_id: Optional[str] = None
    children: List[str] = field(default_factory=list)
    order_queue: List[Order] = field(default_factory=list)
    current_order: Optional[Order] = None
    target_id: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)
    elements: Dict[str, FormationElement] = field(default_factory=dict)
    active: bool = True
    weapon_last_fire: Dict[str, float] = field(default_factory=dict)
    local_tracks: Dict[str, Track] = field(default_factory=dict)
    # Combat stress (mnsim/stress.py): 0..1 suppression from incoming fire, 0..1 morale/cohesion.
    suppression: float = 0.0
    morale: float = 1.0

    @property
    def alive(self) -> bool:
        return self.active and self.state != UnitState.DESTROYED and self.current_strength > 0

    def _composition_key(self):
        """Everything the firepower/crew queries depend on that changes during a run."""
        return (STATE_EPOCH[0], self.active, self.state, self.metadata.get("mount_state"),
                tuple((e.eid, e.count, tuple(e.item_states), len(e.weapons),
                       tuple(w.ammo_remaining for w in e.weapons)) for e in self.elements.values()))

    def _memo(self, name, compute):
        key = self._composition_key()
        cache = self.__dict__.setdefault("_query_memo", {})
        hit = cache.get(name)
        if hit is not None and hit[0] == key:
            return hit[1]
        value = compute()
        cache[name] = (key, value)
        return value

    @property
    def crew_failure_reason(self):
        from .firepower import crew_failure_reason
        return self._memo("crew_failure_reason", lambda: crew_failure_reason(self))

    @property
    def can_observe(self) -> bool:
        # A surviving operator may observe even when too few remain to serve a gun.
        return self.alive and self.crew_failure_reason != 'NO_CREW'

    @property
    def can_communicate(self) -> bool:
        return self.can_observe

    @property
    def current_strength(self) -> float:
        return sum(e.strength for e in self.elements.values())

    @property
    def initial_strength(self) -> float:
        return sum(e.initial_strength for e in self.elements.values())

    @property
    def strength_ratio(self) -> float:
        if self.initial_strength <= 0:
            return 0.0
        return max(0.0, min(1.0, self.current_strength / self.initial_strength))

    @property
    def loss_ratio(self) -> float:
        return 1.0 - self.strength_ratio

    @property
    def personnel(self) -> int:
        return sum(e.count for e in self.elements.values() if e.category.upper() == "PERSONNEL")

    @property
    def initial_personnel(self) -> int:
        return sum(e.initial_count for e in self.elements.values() if e.category.upper() == "PERSONNEL")

    @property
    def equipment(self) -> int:
        return sum(e.count for e in self.elements.values() if e.category.upper() == "EQUIPMENT")

    @property
    def initial_equipment(self) -> int:
        return sum(e.initial_count for e in self.elements.values() if e.category.upper() == "EQUIPMENT")

    @property
    def branch(self) -> str:
        return self.unit_type.branch.upper()

    def distance_to(self, other: "Unit") -> float:
        return math.dist(self.pos, other.pos)

    def capability_available(self, capability: str) -> bool:
        cap = capability.upper()
        return any(w.capability.upper() == cap for _, w in self.operational_weapons())

    def firepower(self, element: FormationElement, weapon: WeaponModel):
        """Runtime participation from current personnel, equipment and ammunition.

        participants counts shooters or staffed weapon systems, not inventory.
        Target acquisition, range, LOS and firing cadence are checked separately.
        """
        from .firepower import participation
        return participation(self, element, weapon)

    def element_exposed(self, element: FormationElement) -> bool:
        """Explicitly enclosed operators are not independent soft targets."""
        provider = self.elements.get(element.metadata.get('protected_by'))
        return provider is None or provider.count <= 0

    def operational_weapons(self) -> List[tuple[FormationElement, WeaponModel]]:
        """Weapons with at least one current participant.  Read-only (no bookkeeping)."""
        def compute():
            return tuple((e, w) for e in self.elements.values() for w in e.weapons
                         if self.firepower(e, w).participants > 0)
        return list(self._memo("operational_weapons", compute))

    def mark_unavailable_fire_cycles(self) -> None:
        """Flag direct-fire cycles whose weapon currently has no participants.

        When the weapon becomes usable again its cycle restarts from 'now' instead of banking a
        backlog of shots accumulated while it was unmanned.  Called once per combat step.
        """
        states = self.metadata.get('_direct_fire_cycle_state')
        if not states:
            return
        for e in self.elements.values():
            for w in e.weapons:
                state = states.get(f'{e.eid}:{w.name}')
                if state is not None and self.firepower(e, w).participants <= 0:
                    state['unavailable'] = True
